# conda env create -f environment.yml
name: pylidar-lite
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy=1.22.4
  - numba
  - pandas
  - scipy
  - rasterio
  - tqdm
  - typed-ast
  - jupyterlab
  - ipywidgets
  - ipykernel
  - matplotlib
  - statsmodels
  - cxx-compiler
  - pip
  - pip:
    - -e .
variables:
  RIVLIB_ROOT: /gws/nopw/j04/nceo_generic/nceo_ucl/TLS/tools/rivlib-2_13_0-x86_64-linux-gcc11
  RDBLIB_ROOT: /gws/nopw/j04/nceo_generic/nceo_ucl/TLS/tools/rdblib-2.5.2-x86_64-linux
  PYLIDAR_CXX_FLAGS: -std=c++11 
